### ISSUE TITLE
Reduce amount of `.clone()`ing

### ISSUE THREAD

**Issue by yavko** [hyprland-community/hyprland-rs#33]
I wrote a lot of this codebase not knowing much on ownership, and now the codebase is riddled with `.clone()`s. This issue exists to track the process of me reducing the usage of `.clone()`

**Comment by tukanoidd** [comment]
Hey, I made a PR adding .iter() functions to data structures through the macros (no breaking changes), so maybe that could be useful internally as well (I'm not that familiar with the entire codebase yet, I just needed to implement this particular functionality for myself since I didn't want to clone data everywhere)

**Comment by yavko** [comment]
This is being pushed for next release, not for `0.3.1` since this will require major rewrites.
